[package]
name = "rustnet-monitor"
version = "0.8.0"
authors = ["domcyrus"]
edition = "2024"
description = "A high-performance, cross-platform network monitoring terminal UI tool built with Rust"
repository = "https://github.com/domcyrus/rustnet"
homepage = "https://github.com/domcyrus/rustnet"
documentation = "https://docs.rs/rustnet-monitor"
readme = "README.md"
license = "Apache-2.0"
keywords = ["network", "monitoring", "tui", "terminal", "packet-capture"]
categories = ["command-line-utilities", "network-programming", "visualization"]
exclude = [
    ".github/",
    "scripts/",
    "tests/",
    "*.log",
    "target/",
    ".gitignore",
]

[[bin]]
name = "rustnet"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
arboard = "3.6"
crossterm = "0.29"
crossbeam = "0.8"
dashmap = "6.1"
dns-lookup = "3.0"
log = "0.4"
num_cpus = "1.17"
pcap = "2.3.0"
pnet_datalink = "0.35"
clap = { version = "4.5", features = ["derive"] }
simple-logging = "2.0"
simplelog = "0.12"
chrono = "0.4"
ratatui = { version = "0.29", features = ["all-widgets"] }
ring = "0.17"
aes = "0.8"

[target.'cfg(target_os = "linux")'.dependencies]
procfs = "0.16"
